### ISSUE TITLE
SCT disabled by UAC prompt

### ISSUE THREAD

**Issue by dkeller93** [d4l3k/go-sct#9]
I'm at `sct 1000` most of the night on Windows 7 64 bit. sct was working fine until I tried to open another powershell in admin mode (C-S-Ret on powershell in the start menu). When the UAC prompt pops up, my screen goes back to (what appears to be) normal. 

When I run `sct 1000` again, nothing happens. When I run `sct <some other number>`, sct works again and I can then `sct 1000` to get back to my desired state.

**Comment by d4l3k** [comment]
That sounds like a bug in Windows. Likely it can be worked around by internally quickly doing "sct 8000" then "sct 1000". I don't actually have a Windows machine to test though.

Do you know if it's an issue on Windows 8, 8.1 and 10?

**Comment by dkeller93** [comment]
I'm not sure. I don't have those windows operating systems.

**Comment by d4l3k** [comment]
Do you want to install the latest patch and see if it fixes it?
